in properties/test.maude
in utils.maude
in id-shortcuts.maude
in preprocessing.maude
in plexil-model-check.maude

mod TEST--MODEL-CHECKER is

pr TEST-BASE .
pr TEST--MODEL-CHECKER--PROPERTIES .
pr TEST--MODEL-CHECKER--UTILS .
  pr TEST--MODEL-CHECKER--ID-SHORTCUTS .
  pr TEST--MODEL-CHECKER--PREPROCESSING .
  pr TEST--MODEL-CHECKER--PLEXIL-MODEL-CHECK .

op test--model-checker : -> TestResults .
eq test--model-checker
  = test--model-checker--properties
  + test--model-checker--utils
  + test--model-checker--id-shortcuts
  + test--model-checker--preprocessing
  + test--model-checker--plexil-model-check
  + test--formatCounterexample
.

op test--formatCounterexample : -> TestResults .
eq test--formatCounterexample =
begin tests

  assert "formatCounterexample a counterexample without finite prefix" from
    anMCResult(
      formatCounterexample(
        counterexample(
          nil
        ,
          { stop | [ interface-history :
              stateLookup('time, nilarg, val(1)) ]
          ,
            'unknownRule
          }
        )
      )
    )
  reaches
    anMCResult(
      NoTransitions
      -->
      Loop {
        Input(
          stateLookup('time, nilarg, val(1))
        )
      }
    )
  end

  assert "formatCounterexample a counterexample with one element interface history" from
    anMCResult(
      formatCounterexample(
        counterexample(
          { stop | [ interface-history :
              commandAck(A, nilarg, CommandAccepted)
              stateLookup('time, nilarg, val(0)) ]
          ,
            'unknownRule
          }
        ,
          { stop | [ interface-history :
              stateLookup('time, nilarg, val(1)) ]
          ,
            'unknownRule
          }
        )
      )
    )
  reaches
    anMCResult(
      Input(
        commandAck(A, nilarg, CommandAccepted)
        stateLookup('time, nilarg, val(0))
      )
      -->
      Loop {
        Input(
          stateLookup('time, nilarg, val(1))
        )
      }
    )
  end

  assert "formatCounterexample a counterexample with two elements interface history" from
    anMCResult(
      formatCounterexample(
        counterexample(
          { stop | [ interface-history :
              (
                commandAck(A, nilarg, CommandAccepted)
                stateLookup('time, nilarg, val(0))
              )
              #
              stateLookup('time, nilarg, val(1))
              ]
          ,
            'unknownRule
          }
        ,
          { stop | [ interface-history :
              stateLookup('time, nilarg, val(2)) ]
          ,
            'unknownRule
          }
        )
      )
    )
  reaches
    anMCResult(
      Input(
        commandAck(A, nilarg, CommandAccepted)
        stateLookup('time, nilarg, val(0))
      )
      -->
      Loop {
        Input(
          stateLookup('time, nilarg, val(2))
        )
      }
    )
  end

end tests .

endm