fmod GENERATORS--COMMAND-ACK is
  protecting GENERATORS--SEQUENCE .

  op command-ack : CommandHandle -> InputGenerator [ctor] .
  eq generate(command-ack(CH),Cfg) = genCommandAcks(Cfg,CH) .
  eq update(command-ack(CH),Cfg,Ins) = command-ack(CH) .
  eq cardinality(command-ack(CH)) = Cardinality(countPerStep : 1, numberOfSteps : infinity) .

  op genCommandAcks : Config CommandHandle -> Inputs .
  eq genCommandAcks(
      [ interface :
        < CmdId . Q : command-on-execution
          | arguments: Args
          , handle: nothing, AtS > CS ] Cfg,
      CH)
    =
      commandAck(CmdId, Args, CH)
      genCommandAcks([ interface : CS ], CH)
  .
  eq genCommandAcks(Cfg, CH) = noInputs [owise] .

  *** Command Ack Generator
  op commandAckGenerator : Inputs Nat -> InputGenerator .
  op commandAckGenerator : Inputs Config Nat Nat GeneratorStatus -> InputGenerator .
  eq commandAckGenerator(EInput,Ites) = commandAckGenerator(EInput,mtsoup,Ites,0,uninitialized) .

  eq generate(commandAckGenerator(EInput,PrevConf,Ites,It,firstIteration),Conf) = EInput .
  eq generate(commandAckGenerator(EInput,PrevConf,Ites,It,started),Conf) =
      if isConsumed?(commandAckGenerator(EInput,PrevConf,Ites,It,started),Conf)
      then nilEInputsList
      else computeCommandAcks(Conf)
      fi .

  eq update(commandAckGenerator(EInput,PrevConf,Ites,0,uninitialized),Conf,EI:Inputs)
    = commandAckGenerator(EInput,Conf,Ites,0,firstIteration) .
  eq update(commandAckGenerator(EInput,PrevConf,Ites,0,firstIteration),Conf,EI:Inputs)
    = commandAckGenerator(EInput,Conf,Ites,1,started) .
  eq update(commandAckGenerator(EInput,PrevConf,Ites,It,started),Conf,EI:Inputs)
    = commandAckGenerator(EInput,Conf,Ites,s It,started) .

  eq isConsumed?(commandAckGenerator(EInput,PrevConf,Ites,It,GenStatus),Conf) = Ites <= It .

  *** Command Ack Generator Extended
  op commandAckGeneratorEx : Inputs Inputs Nat -> InputGenerator .
  op commandAckGeneratorEx : Inputs Inputs Nat Nat GeneratorStatus -> InputGenerator .
  eq commandAckGeneratorEx(EInput,EInput',Ites) = commandAckGeneratorEx(EInput,EInput',Ites,0,uninitialized) .

  var GEN : InputGenerator .
  var EIL'' : EInputsList .

  eq [command-ack-generator-generate-firstIteration] : generate(commandAckGeneratorEx(EInput,EInput',Ites,It,firstIteration),Conf) = EInput .
  ceq [command-ack-generator-generate-cleaning] : generate(GEN,Conf) = EIL'
    if commandAckGeneratorEx(EInput,EInput',Ites,It,cleaning) := GEN
    /\ EInput'' := computeCommandAcks(Conf)
    /\ EIL' := if isConsumed?(GEN,Conf)
                then nilEInputsList
                else EInput''
                fi
  [owise]
  .
  ceq [command-ack-generator-generate-started] : generate(GEN,Conf) = EIL''
    if commandAckGeneratorEx(EInput,EInput',Ites,It,started) := GEN
    /\ EInput'' := computeCommandAcks(Conf)
    /\ EIL := computeLookupCombinations(EInput')
    /\ EIL' := add(EInput'',EIL,nilEInputsList)
    /\ EIL'' := if isConsumed?(GEN,Conf)
                then nilEInputsList
                else EIL'
                fi
    [owise]
    .

  eq update(commandAckGeneratorEx(EInput,EInput',Ites,0,uninitialized),Conf,EI:Inputs)
    = commandAckGeneratorEx(EInput,EInput',Ites,0,firstIteration) .
  eq update(commandAckGeneratorEx(EInput,EInput',Ites,0,firstIteration),Conf,EI:Inputs)
    = commandAckGeneratorEx(EInput,EInput',Ites,1,started) .
  eq update(commandAckGeneratorEx(EInput,EInput',Ites,It,started),Conf,EI:Inputs) =
      if Ites == s It
      then commandAckGeneratorEx(EInput,noInputs,s s s Ites, s It, cleaning)
      else commandAckGeneratorEx(EInput,EInput',Ites,s It,started)
      fi
    .
  eq update(commandAckGeneratorEx(EInput,EInput',Ites,It,cleaning),Conf,EI:Inputs) =
      if Ites == s It
      then noEnvGen
      else commandAckGeneratorEx(EInput,EInput',Ites,s It,cleaning)
      fi
    [owise]
    .

  eq isConsumed?(commandAckGeneratorEx(EInput,EInput',Ites,It,GenStatus),Conf) = Ites <= It .

  *** Infinite Command Ack Generator Extended
  op infiniteCommandAckGeneratorEx : Inputs EInputsList -> InputGenerator .
  op infiniteCommandAckGeneratorEx : Inputs EInputsList GeneratorStatus -> InputGenerator .
  eq infiniteCommandAckGeneratorEx(EInput,EILRef) = infiniteCommandAckGeneratorEx(EInput,EILRef,uninitialized) .

  eq generate(infiniteCommandAckGeneratorEx(EInput,EILRef,uninitialized),Conf) = nilEInputsList .
  eq generate(infiniteCommandAckGeneratorEx(EInput,EILRef,firstIteration),Conf) = EInput .
  ceq generate(infiniteCommandAckGeneratorEx(EInput,EILRef,started),Conf)
    = EIL'
    if EInput'' := computeCommandAcks(Conf)
    /\ EIL := undup(computeLookupCombinationsEx(EILRef))
    /\ EIL' := add(EInput'',EIL,nilEInputsList)
  .

  eq update(infiniteCommandAckGeneratorEx(EInput,EILRef,uninitialized),Conf,EI:Inputs)
    = infiniteCommandAckGeneratorEx(EInput,EILRef,firstIteration) .
  eq update(infiniteCommandAckGeneratorEx(EInput,EILRef,firstIteration),Conf,EI:Inputs)
    = infiniteCommandAckGeneratorEx(EInput,EILRef,started) .
  eq update(infiniteCommandAckGeneratorEx(EInput,EILRef,started),Conf,EI:Inputs)
    = infiniteCommandAckGeneratorEx(EInput,EILRef,started) .

  eq isConsumed?(infiniteCommandAckGeneratorEx(EInput,EILRef,GenStatus),Conf) = false .

  *** Command Abort Ack
  op command-abort-ack : -> InputGenerator [ctor] .
  eq generate(command-abort-ack,Cfg) = genCommandAbortAcks(Cfg) .
  eq update(command-abort-ack,Cfg,Ins) = command-abort-ack .
  eq cardinality(command-abort-ack) = Cardinality(countPerStep : 1, numberOfSteps : infinity) .

  op genCommandAbortAcks : Config -> Inputs .
  eq genCommandAbortAcks(
      [ interface :
        < CmdId . Q : command-on-execution
          | arguments: Args
          , abort: CommandAbortInvoked
          , AtS >
        CS ]
      Cfg)
    =
      commandAbort(CmdId,Args,val(true))
      genCommandAbortAcks([ interface : CS ]) .
  eq genCommandAbortAcks(Cfg) = noInputs [owise] .

  *** Common functions
  op computeCommandAcks : Config -> Inputs .
  eq computeCommandAcks( [ interface : < CmdId . Q : command-on-execution | arguments: Args, handle: nothing, AtS > CS ] Conf )
      = commandAck(CmdId, Args, CommandSuccess) computeCommandAcks([ interface : CS ]) .
  eq computeCommandAcks( Conf )
      = noInputs [owise] .

  op computeLookupCombinations : Inputs -> EInputsList .
  eq computeLookupCombinations(ExIn) = computeLookupCombinations(ExIn,noInputs) .

  op computeLookupCombinations : Inputs EInputsList -> EInputsList .
  eq computeLookupCombinations(In ExIn,ExInLst)
      = computeLookupCombinations(ExIn, combine(In,ExInLst,nilEInputsList)) .
  eq computeLookupCombinations(noInputs,ExInLst)
      = ExInLst .

  op computeLookupCombinationsEx : EInputsList -> EInputsList .
  eq computeLookupCombinationsEx(EILRef) = computeLookupCombinationsEx(EILRef,noInputs) .

  op computeLookupCombinationsEx : EInputsList EInputsList -> EInputsList .
  ceq computeLookupCombinationsEx(ExIn # EILRef,ExInLst)
      = computeLookupCombinationsEx(EILRef, combineEx(EIL,ExInLst,nilEInputsList))
    if EIL := computeLookupCombinations'(ExIn)
  .
  eq computeLookupCombinationsEx(nilEInputsList,ExInLst)
      = ExInLst .

  op computeLookupCombinations' : Inputs -> EInputsList .
  eq computeLookupCombinations'(In ExIn) = In # computeLookupCombinations'(ExIn) .
  eq computeLookupCombinations'(noInputs) = noInputs .

  op toEInputsList : Inputs -> EInputsList .
  eq toEInputsList(ExIn) = toEInputsList(ExIn,nilEInputsList) .

  op toEInputsList : Inputs EInputsList -> EInputsList .
  eq toEInputsList(In ExIn,ExInLstAcc) = toEInputsList(ExIn,In # ExInLstAcc) .
  eq toEInputsList(noInputs,ExInLstAcc) = noInputs # ExInLstAcc .

  op combine : Inputs EInputsList EInputsList -> EInputsList .
  eq combine(EIns,ExIn # ExInLst, ExInLstAcc)
      = combine(EIns,ExInLst,(EIns ExIn) # ExIn # ExInLstAcc) .
  eq combine(EIns,nilEInputsList, ExInLstAcc)
      = ExInLstAcc [owise] .

  op combineEx : EInputsList EInputsList EInputsList -> EInputsList .
  eq combineEx(ExIn # ExInLst,EILRef, ExInLstAcc)
      = combineEx(ExInLst,EILRef,combine(ExIn,EILRef,ExInLstAcc)) .
  eq combineEx(nilEInputsList,EILRef, ExInLstAcc)
      = ExInLstAcc [owise] .

  op undup : EInputsList -> EInputsList .
  eq undup(EInLst:EInputsList # EIns # EInLst':EInputsList # EIns # EInLst'':EInputsList)
   = undup(EInLst:EInputsList # EIns # EInLst':EInputsList # EInLst'':EInputsList) .
  eq undup(EInLst:EInputsList # noInputs # EInLst':EInputsList)
   = undup(EInLst:EInputsList #                    EInLst':EInputsList) .
  eq undup(EIL) = EIL [owise] .

  op add : Inputs EInputsList -> EInputsList .
  eq add(EInput,ExInLst) = add(EInput,ExInLst,nilEInputsList) .

    op add : Inputs EInputsList EInputsList -> EInputsList .
    eq add(EInput,ExIn # ExInLst, ExInLstAcc) = add(EInput,ExInLst,(EInput ExIn) # ExInLstAcc) .
    eq add(EInput,nilEInputsList, ExInLstAcc) = ExInLstAcc .

  vars Args  : Arguments .
  vars AtS   : AttributeSet .
  vars CH : CommandHandle .
  vars CS    : Configuration .
  vars Q     : Qualified .
  vars CmdId : Identifier .
  vars Cfg : Config .
  vars Conf Conf' : Config .
  vars EInput EInput' EInput'' EInput''' : Inputs .
  vars EIL : EInputsList .
  vars It Ites : Nat .
  vars PrevConf : Config .
  vars EILChosen : Inputs .
  vars EIL' : EInputsList .
  vars EILRef : EInputsList .
  vars GenStatus : GeneratorStatus .
  vars In : Input .
  vars Ins : Inputs .
  vars EIns : Inputs .
  vars ExIn : Inputs .
  vars ExInLst ExInLstAcc : EInputsList .
endfm
