mod TEST--GENERATORS--PLEXILTEST is
  protecting TEST-BASE .

  op test--generators--plexiltest : -> TestResults .
  eq test--generators--plexiltest =
begin tests

  assert "plexiltest 1" from
    anInputsSet(
      generate(
        plexiltest(nilEInputsList)
       ,emptyConfig
      )
    )
  reaches
    anInputsSet(
      empty
    )
  end

  assert "plexiltest 2" from
    anInputsSet(
      generate(
        plexiltest(noInputs)
       ,mtsoup
      )
    )
  reaches
    anInputsSet(
      noInputs
    )
  end

  assert "plexiltest 3" from
    anInputsSet(
      generate(
        plexiltest(stateLookup('id,nilarg, val(1)))
       ,mtsoup
      )
    )
  reaches
    anInputsSet(
      stateLookup('id,nilarg, val(1))
    )
  end

  assert "plexiltest 4" from
    anInputsSet(
      generate(
        plexiltest(nilEInputsList),
        (emptyConfig // [ nodes :
          < 'id2 : empty |
            status: waiting,
            outcome: none,
            active: false,
            repeatc: const(val(false)),
            startc: const(val(true)),
            endc: const(val(true)),
            exitc: const(val(false)),
            post: const(val(true)),
            skip: const(val(false)),
            pre: const(val(true)),
            inv: const(val(true)) > ]
        )
      )
    )
  reaches
    anInputsSet(
      noInputs
    )
  end

  assert "plexiltest 5" from
    anInputsSet(
      generate(
        plexiltest(nilEInputsList)
       ,
          (emptyConfig // [ nodes :
            < 'id2 : empty |
              status: waiting,
              outcome: none,
              active: false,
              repeatc: const(val(false)),
              startc: const(val(false)),
              endc: const(val(true)),
              exitc: const(val(false)),
              post: const(val(true)),
              skip: const(val(false)),
              pre: const(val(true)),
              inv: const(val(true)) > ])
      )
    )
  reaches
    anInputsSet(
      empty
    )
  end

  assert "plexiltest Update 1" from
    aGenerator(
      update(
        plexiltest(nilEInputsList)
       ,[ nodes : < 'id3 : list | status: inactive > ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(nilEInputsList)
    )
  end

  assert "plexiltest Update 2" from
    aGenerator(
      update(
        plexiltest(noInputs)
       ,(emptyConfig // [ nodes :
            < 'id2 : empty |
              status: waiting,
              outcome: none,
              active: false,
              repeatc: const(val(false)),
              startc: const(val(false)),
              endc: const(val(true)),
              exitc: const(val(false)),
              post: const(val(true)),
              skip: const(val(false)),
              pre: const(val(true)),
              inv: const(val(true)) > ])
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(nilEInputsList)
    )
  end

  assert "plexiltest Update 3" from
    aGenerator(
      update(
        plexiltest(noInputs # stateLookup('id,nilarg, val(1)))
       ,[ nodes : < 'id3 : list | status: inactive > ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(stateLookup('id,nilarg, val(1)))
    )
  end

  assert "plexiltest Update ignores generators 1" from
    aGenerator(
      update(
        plexiltest(noInputs # stateLookup('id,nilarg, val(1)))
       ,[ nodes : < 'id3 : list | status: inactive > ]
        [ generator : zero ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(stateLookup('id,nilarg, val(1)))
    )
  end

  assert "plexiltest Update ignores generators 2" from
    aGenerator(
      update(
        plexiltest(nilEInputsList)
       ,[ nodes : < 'id3 : list | status: inactive > ]
        [ generator : zero ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(nilEInputsList)
    )
  end

  assert "plexiltest Update ignores interface-history 1" from
    aGenerator(
      update(
        plexiltest(noInputs # stateLookup('id,nilarg, val(1)))
       ,[ nodes : < 'id3 : list | status: inactive > ]
        [ interface-history : nilEInputsList ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(stateLookup('id,nilarg, val(1)))
    )
  end

  assert "plexiltest Update ignores interface-history 2" from
    aGenerator(
      update(
        plexiltest(nilEInputsList)
       ,[ nodes : < 'id3 : list | status: inactive > ]
        [ interface-history : nilEInputsList ]
       ,noInputs
      )
    )
  reaches
    aGenerator(
      plexiltest(nilEInputsList)
    )
  end

end tests
.

endm
