in cache.maude
in cache-update.maude
in cache-integration.maude
in micro.maude
in macro.maude
in reductions.maude
in syncred.maude
in values.maude

mod TEST--REDUCTIONS is

  pr TEST--REDUCTIONS--CACHE .
  pr TEST--REDUCTIONS--CACHE-UPDATE .
  pr TEST--REDUCTIONS--CACHE-INTEGRATION .
  pr TEST--REDUCTIONS--MICRO .
  pr TEST--REDUCTIONS--MACRO .
  pr TEST--REDUCTIONS--REDUCTIONS .
  pr TEST--REDUCTIONS--SYNCRED .
  pr TEST--REDUCTIONS--VALUES .

  op reductions--tests : -> TestResults .

  eq reductions--tests =
    test--reductions--cache
    + test--reductions--cache-update
    + test--reductions--cache-integration
    + micro--reductions--tests
    + test--reductions--macro
    + test--reductions--reductions
    + test--reductions--syncred
    + values--reductions--tests
    .

endm