mod TEST--MODEL-CHECKER--PROPERTIES--IS-TRUE is

pr TEST-BASE .

op test--model-checker--properties--isTrue? : -> TestResults .
eq test--model-checker--properties--isTrue? =
begin tests
  assert "isTrue? accepts expressions depending on nodes" from
    testBool(
      ( stop |
        [ memory : none ]
        [ nodes : < 'A : empty | outcome: skipped > ]
        [ interface : none ]
        [ environment : mtenvironment ]
      ) |= isTrue?(isOutcome?('A,skipped))
    )
  reaches
    testBool(
      true
    )
  end
end tests .

endm
