fmod EXTENDED-EXPRESSION is

extending EXPRESSION .
extending FUNCTION .

protecting COMMAND-HANDLE .
protecting INT .
protecting OUTCOME .
protecting PARAMETER .
protecting QUALIFIED .
protecting STATUS .
protecting TIMEPOINT .
protecting VALUE .

 op _+_           : Expression Expression -> Expression [prec 13 format (o sc o o)] .
 op _-_           : Expression Expression -> Expression [prec 13 format (o sc o o)] .
 op _*_           : Expression Expression -> Expression [prec 12 format (o sc o o)] .
 op _/_           : Expression Expression -> Expression [prec 12 format (o sc o o)] .
 op _rem_         : Expression Expression -> Expression [prec 12 format (o sc o o)] .
 op _max_         : Expression Expression -> Expression [prec 14 format (o sc o o)] .
 op _min_         : Expression Expression -> Expression [prec 14 format (o sc o o)] .
 op _<_           : Expression Expression -> Expression [prec 15 format (o sc o o)] .
 op _<=_          : Expression Expression -> Expression [prec 15 format (o sc o o)] .
 op _>_           : Expression Expression -> Expression [prec 15 format (o sc o o)] .
 op _>=_          : Expression Expression -> Expression [prec 15 format (o sc o o)] .
 op _and_         : Expression Expression -> Expression [prec 18 format (o sc o o)] .
 op _or_          : Expression Expression -> Expression [prec 18 format (o sc o o)] .
 op _equ_         : Expression Expression -> Expression [prec 20 format (o sc o o)] .
 op _nequ_        : Expression Expression -> Expression [prec 20 format (o sc o o)] .
 op not_          : Expression            -> Expression [prec 17 format (c o o)] .
 op isKnown       : Expression            -> Expression .
 op noChildFailed           :             -> Expression [ctor] .
 op noChildFailed           : NeQualified -> Expression [ctor] .
 op isFinished?             : NeQualified -> Expression .
 op hasSucceeded?           : NeQualified -> Expression .
 op hasPostconditionFailed? : NeQualified -> Expression .
 op hasSkipped?             : NeQualified -> Expression .
 op hasRcvAck?              : NeQualified -> Expression .

op lookup             : NeQualified Parameters       -> Lookup [format (b o)] .
op lookup             : NeQualified Arguments        -> Lookup [format (b o)] .
op lookupOnChange     : NeQualified Parameters Value -> Lookup [format (b o)] .
op lookupOnChange     : NeQualified Arguments  Value -> Lookup [format (b o)] .

vars Q Q' : NeQualified .
vars V    : Value .
vars F    : Function .
vars E    : Expression .
vars Pars : Parameters .

*** Function Ids
**** Absolute value (of integers and reals)
 op absp    : -> Function .
**** Square root (of reals)
 op sqrt    : -> Function .
**** Ceiling (of integers and reals)
 op ceiling : -> Function .
**** Floor (of integers and reals)
 op floor   : -> Function .
**** Round (of integers and reals)
 op round   : -> Function .
**** Trunc (of integers and reals)
 op trunc   : -> Function .
**** Real to int (of integers and reals)
 op real-to-int : -> Function .

*** Predicates on processes
 op isStatus?         : NeQualified Status      -> Expression .
 op isOutcome?        : NeQualified Outcome     -> Expression .
 op isOutcomeFailure? : NeQualified             -> Expression .
 op isOutcomeSuccess? : NeQualified             -> Expression .
 op isFailure?        : NeQualified FailureType -> Expression .
 op areChildren?      : NeQualified Status      -> Expression .
 op areChildren?      : Status                  -> Expression .
 op cmdHandleRcv?     : NeQualified             -> Expression .
 op cmdHandleRcv?     :                         -> Expression .
 op cmdHandleIs?      : NeQualified CommandHandle -> Expression .

*** Node timepoints
 op timepoint         : NeQualified Status Timepoint -> Expression .


***( Expressions on commands )

op numberOfCommandsOnExecutionWithId : Identifier -> Expression .

endfm
